services:
  - type: web
    name: voicebot-backend
    env: python
    region: singapore # You can change this to your preferred Render region
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Specify the Python version you want to use
      - key: GROQ_API_KEY
        sync: false
      - key: BHASHINI_API_KEY
        sync: false
      - key: BHASHINI_USER_ID
        sync: false
      - key: BHASHINI_PIPELINE_ID
        sync: false
      - key: DATABASE_POOLER_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
